### ISSUE TITLE
Update examples to use Pyroscope

### ISSUE THREAD

**Issue by Rperry2174** [grafana/intro-to-mltp#40]
Needs to update this example to use Pyroscope here (and also rename all mentions of phlare to Pyroscope)

**Comment by hedss** [comment]
Have now properly updated Pyroscope to the `grafana/pyroscope` Docker registry and made appropriate GRAgent config changes. See #58. Cheers Ryan :)

**Comment by hedss** [comment]
Merged and closed.

**Comment by scarson** [comment]
Hi @hedss, I noticed an instance of Phlare left in a comment here:
https://github.com/grafana/intro-to-mltp/blob/14f8df4745b93a932cd2c4bf37e9ff1e8d3ad909/alloy/config.alloy#L17
