### ISSUE TITLE
Why multiplying by `55` in Request Rate panel in `MLT dashboard`?

### ISSUE THREAD

**Issue by gczarnocki** [grafana/intro-to-mltp#54]
Hello. I am wondering why there's a multiplication by `55` in MLT dashboard in `Request Rate` panel, here:

```text
          "expr": "(sum by (http_target)(rate(traces_spanmetrics_latency_sum{http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m]))) / (sum by (http_target)(rate(traces_spanmetrics_latency_count{http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m]))) * 55",
```

Thank you for your reply!

**Comment by hedss** [comment]
Hi @gczarnocki 
This was actually originally to boost the request numbers up (this repo actually is buried in the roots of my interview all those years ago). I'll raise a PR to drop this, as artificial numbers aren't required anymore esp. now we've included k6.

Also, apologies for the delay in response, first time I've been able to properly come back to the repo in a while!

**Comment by hedss** [comment]
Changed in #58

**Comment by hedss** [comment]
Merged and closed.
