### ISSUE TITLE
Database queries are all failing

### ISSUE THREAD

**Issue by scarolan** [grafana/intro-to-mltp#76]
Not sure if this is intended but the database pod logs show a steady stream of 'violates not-null constraint' errors

`│ 2024-02-29 15:20:13.081 UTC [67] ERROR:  null value in column "name" of relation "illithid" violates not-null constraint                                                                                            ││ 2024-02-29 15:20:13.081 UTC [67] DETAIL:  Failing row contains (726, null).                                                                                                                                         ││ 2024-02-29 15:20:13.081 UTC [67] STATEMENT:  INSERT INTO illithid(name) VALUES ($1)                                                                                                                                 ││ 2024-02-29 15:20:16.259 UTC [70] ERROR:  null value in column "name" of relation "owlbear" violates not-null constraint                                                                                             ││ 2024-02-29 15:20:16.259 UTC [70] DETAIL:  Failing row contains (753, null).                                                                                                                                         ││ 2024-02-29 15:20:16.259 UTC [70] STATEMENT:  INSERT INTO owlbear(name) VALUES ($1)                                                                                                                                  ││ 2024-02-29 15:20:17.631 UTC [110] LOG:  invalid length of startup packet                                                                                                                                            ││ 2024-02-29 15:20:20.862 UTC [67] ERROR:  null value in column "name" of relation "unicorn" violates not-null constraint                                                                                             ││ 2024-02-29 15:20:20.862 UTC [67] DETAIL:  Failing row contains (763, null).                                                                                                                                         ││ 2024-02-29 15:20:20.862 UTC [67] STATEMENT:  INSERT INTO unicorn(name) VALUES ($1)                                                                                                                                  ││ 2024-02-29 15:20:24.071 UTC [69] ERROR:  null value in column "name" of relation "beholder" violates not-null constraint                                                                                            ││ 2024-02-29 15:20:24.071 UTC [69] DETAIL:  Failing row contains (795, null).                                                                                                                                         ││ 2024-02-29 15:20:24.071 UTC [69] STATEMENT:  INSERT INTO beholder(name) VALUES ($1)                                                                                                                                 ││ 2024-02-29 15:20:27.447 UTC [67] ERROR:  null value in column "name" of relation "beholder" violates not-null constraint                                                                                            ││ 2024-02-29 15:20:27.447 UTC [67] DETAIL:  Failing row contains (797, null).                                                                                                                                         ││ 2024-02-29 15:20:27.447 UTC [67] STATEMENT:  INSERT INTO beholder(name) VALUES ($1)                                                                                                                                 ││ 2024-02-29 15:20:28.172 UTC [67] ERROR:  null value in column "name" of relation "beholder" violates not-null constraint                                                                                            ││ 2024-02-29 15:20:28.172 UTC [67] DETAIL:  Failing row contains (798, null).                                                                                                                                         ││ 2024-02-29 15:20:28.172 UTC [67] STATEMENT:  INSERT INTO beholder(name) VALUES ($1)                                                                                                                                 ││ 2024-02-29 15:20:30.419 UTC [70] ERROR:  null value in column "name" of relation "unicorn" violates not-null constraint                                                                                             ││ 2024-02-29 15:20:30.419 UTC [70] DETAIL:  Failing row contains (768, null).                                                                                                                                         ││ 2024-02-29 15:20:30.419 UTC [70] STATEMENT:  INSERT INTO unicorn(name) VALUES ($1)  `

**Comment by hedss** [comment]
Hi @scarolan 
These are intentional and are actually used to show an erroring workflow in the dashboards. Without these, there would no errors, and we'd have nothing to show for an investigation error flow. :D
